//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Brands
    {
        public int BrandID { get; set; }
        public Nullable<int> CategoriesID { get; set; }
        public string BrandName { get; set; }
        public string Brandimage { get; set; }
    }
}
